### PR TITLE
conform with specs

### PR DESCRIPTION
**Pull request by MohammadYounes**

### CODE REVIEW

**Comment by TrySound** [comment]
Add please this test case `55/55`

**Comment by MohammadYounes** [comment]
Like `rgba( 0, 55/55, 0/*,.5*/ )` ?

**Comment by TrySound** [comment]
@MohammadYounes Yeah, this will be fine.

**Comment by MohammadYounes** [comment]
Updated, I also added: *should parse comments at the end of url functions with quoted first argument* `url( "/demo/bg.png" /*comment*/ )`

**Comment by TrySound** [comment]
@MohammadYounes `/` is divider. It should be parsed.

**Comment by MohammadYounes** [comment]
@TrySound Done!

**Comment by TrySound** [comment]
@MohammadYounes That's much better. Thanks!

**Comment by TrySound** [comment]
@MohammadYounes Published.

**Pull request merged**
