### PR TITLE
chore(release): 4.0.0

### PR DESCRIPTION
**Pull request by evilebottnawi**
/cc @TrySound

### CODE REVIEW

**Comment by TrySound** [comment]
@evilebottnawi drop node v6 support. Or does stylelint still support it?

**Comment by evilebottnawi** [comment]
Yes, we can drop node@6

**Comment by evilebottnawi** [comment]
@TrySound should we setup `engine` in `package.json`

**Comment by TrySound** [comment]
I think mentioning in changelog should be enough.

**Comment by evilebottnawi** [comment]
@TrySound Can i merge this and do release?

**Pull request merged**
